-- MySQL Script generated by MySQL Workbench
-- Sun Nov 19 17:57:29 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema trabajoPractico
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema trabajoPractico
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `trabajoPractico` DEFAULT CHARACTER SET utf8 ;
USE `trabajoPractico` ;

-- -----------------------------------------------------
-- Table `trabajoPractico`.`MesaAyuda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `trabajoPractico`.`MesaAyuda` (
  `idMesaAyuda` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`idMesaAyuda`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `trabajoPractico`.`Operador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `trabajoPractico`.`Operador` (
  `idOperador` INT NOT NULL AUTO_INCREMENT,
  `MesaAyuda_idMesaAyuda` INT NOT NULL,
  PRIMARY KEY (`idOperador`),
  INDEX `fk_Operador_MesaAyuda1_idx` (`MesaAyuda_idMesaAyuda` ASC) VISIBLE,
  CONSTRAINT `fk_Operador_MesaAyuda1`
    FOREIGN KEY (`MesaAyuda_idMesaAyuda`)
    REFERENCES `trabajoPractico`.`MesaAyuda` (`idMesaAyuda`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `trabajoPractico`.`TipoIncidente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `trabajoPractico`.`TipoIncidente` (
  `idTipoIncidente` INT NOT NULL AUTO_INCREMENT,
  `Descripcion` VARCHAR(255) NOT NULL,
  `TipoIncidente` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idTipoIncidente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `trabajoPractico`.`Tecnico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `trabajoPractico`.`Tecnico` (
  `idTecnico` INT NOT NULL AUTO_INCREMENT,
  `TipoIncidente_idTipoIncidente` INT NOT NULL,
  `Nombre` VARCHAR(45) NOT NULL,
  `Especialidades` VARCHAR(45) NOT NULL,
  `Tiempo_Estimado_Por_Incidente` INT NOT NULL,
  PRIMARY KEY (`idTecnico`),
  INDEX `fk_Tecnico_TipoIncidente1_idx` (`TipoIncidente_idTipoIncidente` ASC) VISIBLE,
  CONSTRAINT `fk_Tecnico_TipoIncidente1`
    FOREIGN KEY (`TipoIncidente_idTipoIncidente`)
    REFERENCES `trabajoPractico`.`TipoIncidente` (`idTipoIncidente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `trabajoPractico`.`Servicio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `trabajoPractico`.`Servicio` (
  `idServicio` INT NOT NULL AUTO_INCREMENT,
  `Tecnico_idTecnico` INT NOT NULL,
  `TIpo_de_Servicio` VARCHAR(45) NOT NULL,
  `Cliente_Asociado` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idServicio`),
  INDEX `fk_Servicio_Tecnico1_idx` (`Tecnico_idTecnico` ASC) VISIBLE,
  CONSTRAINT `fk_Servicio_Tecnico1`
    FOREIGN KEY (`Tecnico_idTecnico`)
    REFERENCES `trabajoPractico`.`Tecnico` (`idTecnico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `trabajoPractico`.`Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `trabajoPractico`.`Cliente` (
  `idCliente` INT NOT NULL AUTO_INCREMENT,
  `Operador_idOperador` INT NOT NULL,
  `Servicio_idServicio` INT NOT NULL,
  `Nombre_cliente` VARCHAR(45) NOT NULL,
  `DNI` INT NOT NULL,
  `Razon_Social` VARCHAR(45) NOT NULL,
  `C.U.I.T` INT NOT NULL,
  PRIMARY KEY (`idCliente`),
  INDEX `fk_Cliente_Operador_idx` (`Operador_idOperador` ASC) VISIBLE,
  INDEX `fk_Cliente_Servicio1_idx` (`Servicio_idServicio` ASC) VISIBLE,
  CONSTRAINT `fk_Cliente_Operador`
    FOREIGN KEY (`Operador_idOperador`)
    REFERENCES `trabajoPractico`.`Operador` (`idOperador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Cliente_Servicio1`
    FOREIGN KEY (`Servicio_idServicio`)
    REFERENCES `trabajoPractico`.`Servicio` (`idServicio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `trabajoPractico`.`Incidente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `trabajoPractico`.`Incidente` (
  `idIncidente` INT NOT NULL AUTO_INCREMENT,
  `Operador_idOperador` INT NOT NULL,
  `Servicio_idServicio` INT NOT NULL,
  `Tecnico_idTecnico` INT NOT NULL,
  `TipoIncidente_idTipoIncidente` INT NOT NULL,
  `TipoIncidente` VARCHAR(45) NOT NULL,
  `Detalle` VARCHAR(255) NOT NULL,
  `Descripcion` VARCHAR(255) NOT NULL,
  `Fecha_Ingreso` DATE NOT NULL,
  `Fecha_Resolucion` DATE NOT NULL,
  `Estado` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idIncidente`),
  INDEX `fk_Incidente_Operador1_idx` (`Operador_idOperador` ASC) VISIBLE,
  INDEX `fk_Incidente_Servicio1_idx` (`Servicio_idServicio` ASC) VISIBLE,
  INDEX `fk_Incidente_Tecnico1_idx` (`Tecnico_idTecnico` ASC) VISIBLE,
  INDEX `fk_Incidente_TipoIncidente1_idx` (`TipoIncidente_idTipoIncidente` ASC) VISIBLE,
  CONSTRAINT `fk_Incidente_Operador1`
    FOREIGN KEY (`Operador_idOperador`)
    REFERENCES `trabajoPractico`.`Operador` (`idOperador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Incidente_Servicio1`
    FOREIGN KEY (`Servicio_idServicio`)
    REFERENCES `trabajoPractico`.`Servicio` (`idServicio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Incidente_Tecnico1`
    FOREIGN KEY (`Tecnico_idTecnico`)
    REFERENCES `trabajoPractico`.`Tecnico` (`idTecnico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Incidente_TipoIncidente1`
    FOREIGN KEY (`TipoIncidente_idTipoIncidente`)
    REFERENCES `trabajoPractico`.`TipoIncidente` (`idTipoIncidente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
